/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bikeshow.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Denilson Petrônio de Almeida
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenCad = new javax.swing.JMenu();
        MenCadCli = new javax.swing.JMenuItem();
        MemCadUsu = new javax.swing.JMenuItem();
        MemCadFornec = new javax.swing.JMenuItem();
        MemCadProdutos = new javax.swing.JMenuItem();
        MemREl = new javax.swing.JMenu();
        MemRelSer = new javax.swing.JMenuItem();
        MemRelVend = new javax.swing.JMenuItem();
        MemProd = new javax.swing.JMenu();
        MemProdPecas = new javax.swing.JMenuItem();
        MemProdBicy = new javax.swing.JMenuItem();
        MemProdVend = new javax.swing.JMenuItem();
        MenEstq = new javax.swing.JMenu();
        MemEstqEnt = new javax.swing.JMenuItem();
        MemEstqSai = new javax.swing.JMenuItem();
        MemOpc = new javax.swing.JMenu();
        MemOpcSai = new javax.swing.JMenuItem();
        MemAjuda = new javax.swing.JMenu();
        MemAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal Bikeshow");
        setFont(new java.awt.Font("Alef", 2, 14)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Desktop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/iconfinder_bicycle_48007.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData.setText("Data");

        MenCad.setForeground(new java.awt.Color(0, 0, 153));
        MenCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/cad.png.png"))); // NOI18N
        MenCad.setText("Cadrastro");
        MenCad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/user_group_skin_type_7_48px.png"))); // NOI18N
        MenCadCli.setText("Clientes");
        MenCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadCliActionPerformed(evt);
            }
        });
        MenCad.add(MenCadCli);

        MemCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MemCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/iconfinder_User_131997.png"))); // NOI18N
        MemCadUsu.setText("Usuarios");
        MemCadUsu.setEnabled(false);
        MemCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemCadUsuActionPerformed(evt);
            }
        });
        MenCad.add(MemCadUsu);

        MemCadFornec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        MemCadFornec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/service_40px.png"))); // NOI18N
        MemCadFornec.setText("Fornecedores");
        MemCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemCadFornecActionPerformed(evt);
            }
        });
        MenCad.add(MemCadFornec);

        MemCadProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        MemCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/iconfinder_ProductHunt_4700661.png"))); // NOI18N
        MemCadProdutos.setText("Produtos");
        MenCad.add(MemCadProdutos);

        Menu.add(MenCad);

        MemREl.setForeground(new java.awt.Color(0, 0, 153));
        MemREl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/system_report_48px.png"))); // NOI18N
        MemREl.setText("Relatorio");
        MemREl.setEnabled(false);
        MemREl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MemRelSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        MemRelSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/settings5_116147.png"))); // NOI18N
        MemRelSer.setText("Os");
        MemREl.add(MemRelSer);

        MemRelVend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        MemRelVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/sale_48px.png"))); // NOI18N
        MemRelVend.setText("vendas");
        MemREl.add(MemRelVend);

        Menu.add(MemREl);

        MemProd.setForeground(new java.awt.Color(0, 0, 153));
        MemProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/move_by_trolley_48px.png"))); // NOI18N
        MemProd.setText("Produtos");
        MemProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MemProdPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/services_40px.png"))); // NOI18N
        MemProdPecas.setText("peças");
        MemProd.add(MemProdPecas);

        MemProdBicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/travel_bicycle_1743.png"))); // NOI18N
        MemProdBicy.setText("bicicletas");
        MemProd.add(MemProdBicy);

        MemProdVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/sale_48px.png"))); // NOI18N
        MemProdVend.setText("Vendas");
        MemProd.add(MemProdVend);

        Menu.add(MemProd);

        MenEstq.setForeground(new java.awt.Color(0, 0, 153));
        MenEstq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/product_48px.png"))); // NOI18N
        MenEstq.setText("Estoque");
        MenEstq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MemEstqEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/inbox-4_icon-icons.com_65988.png"))); // NOI18N
        MemEstqEnt.setText("Entrada");
        MenEstq.add(MemEstqEnt);

        MemEstqSai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/archive-1_icon-icons.com_66024.png"))); // NOI18N
        MemEstqSai.setText("Saida");
        MenEstq.add(MemEstqSai);

        Menu.add(MenEstq);

        MemOpc.setForeground(new java.awt.Color(0, 0, 153));
        MemOpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/information_40px.png"))); // NOI18N
        MemOpc.setText("Opções");
        MemOpc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MemOpcSai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/iconfinder_Log Out_27856 (1).png"))); // NOI18N
        MemOpcSai.setText("Sair");
        MemOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemOpcSaiActionPerformed(evt);
            }
        });
        MemOpc.add(MemOpcSai);

        Menu.add(MemOpc);

        MemAjuda.setForeground(new java.awt.Color(0, 0, 153));
        MemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/help_48px.png"))); // NOI18N
        MemAjuda.setText("Ajuda");
        MemAjuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MemAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        MemAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bikeshow/icones/information_30px.png"))); // NOI18N
        MemAjudaSobre.setText("Sobre");
        MemAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemAjudaSobreActionPerformed(evt);
            }
        });
        MemAjuda.add(MemAjudaSobre);

        Menu.add(MemAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(782, 782, 782)
                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addComponent(Desktop)
        );

        setSize(new java.awt.Dimension(990, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas abaixo substituem a label lblData pela data atual do 
        //sistema ao inicializar o form.
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MemOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemOpcSaiActionPerformed
        // Exibe uma caixa de diálogo.
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja Sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MemOpcSaiActionPerformed

    private void MemAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemAjudaSobreActionPerformed
        // Chamando a tela sobre.
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MemAjudaSobreActionPerformed

    private void MemCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemCadUsuActionPerformed
        // As linhas abaixo irão abrir o form telaususario dentro do desktopPane.
        TelaUsuario usuario =new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_MemCadUsuActionPerformed

    private void MenCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadCliActionPerformed
        // Chamando a tela cliente.
        TelaClientes clientes = new TelaClientes();
        clientes.setVisible(true);
        Desktop.add(clientes);
    }//GEN-LAST:event_MenCadCliActionPerformed

    private void MemCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemCadFornecActionPerformed
        // Chamando a tela fornecedores.
	TelaFornecedores fornecedores = new TelaFornecedores();
	fornecedores.setVisible(true);
	Desktop.add(fornecedores);
    }//GEN-LAST:event_MemCadFornecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu MemAjuda;
    private javax.swing.JMenuItem MemAjudaSobre;
    private javax.swing.JMenuItem MemCadFornec;
    private javax.swing.JMenuItem MemCadProdutos;
    public static javax.swing.JMenuItem MemCadUsu;
    private javax.swing.JMenuItem MemEstqEnt;
    private javax.swing.JMenuItem MemEstqSai;
    private javax.swing.JMenu MemOpc;
    private javax.swing.JMenuItem MemOpcSai;
    private javax.swing.JMenu MemProd;
    private javax.swing.JMenuItem MemProdBicy;
    private javax.swing.JMenuItem MemProdPecas;
    private javax.swing.JMenuItem MemProdVend;
    public static javax.swing.JMenu MemREl;
    private javax.swing.JMenuItem MemRelSer;
    private javax.swing.JMenuItem MemRelVend;
    private javax.swing.JMenu MenCad;
    private javax.swing.JMenuItem MenCadCli;
    private javax.swing.JMenu MenEstq;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
